spring.application.name=ms-catalogo

# 2. Agrega la direccion de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# 3. (Opcional) Frecuencia de envío de latidos (útil en desarrollo)
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

spring.datasource.url=jdbc:mysql://localhost:3306/db_catalogo
server.port=8082
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true




# URL de servicio de storage (si se implementa-Por mientras estara comentado ya que se usara Eureka)
#storage.service.url=http://localhost:8088

